name = "Friendships"
uuid = "e94ec409-90a0-4317-a06f-0e8b9c2ca529"
version = "0.1.0"
authors = ["nanaaaicha <nanaaaichat@gmail.com>"]

[deps]
GraphPlot = "a2cc645c-3eea-5389-862e-a155d0052231"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
GraphPlot = "0.6.1"
Graphs = "1.13.1"
LightGraphs = "1.0.2"
LinearAlgebra = "1.12.0"
Plots = "1.41.1"
Random = "1.11.0"
